DVD/DVDLibrary/Controllers/MovieManagerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DVDLibrary.Models;
using DVDLibrary.BLL;
using System.Net;
using DVDLibrary.Data;

namespace DVDLibrary.Controllers
{
    [HandleError]
    public class MovieManagerController : Controller
    {
        
        // GET: MovieManager
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Index(int? id ,string searchString)
        {
            //SearchResult
            var manager = new Manager();
            Response<List<Movie>> response = manager.GetAllMovies(searchString);
            List<Movie> movieList = response.Data;
            TempData["results"] = movieList;
            return RedirectToAction("SearchResult");
        }
  
        public ActionResult SearchResult()
        {
            var res = TempData["results"];

            return View(res);
        }

        public ActionResult Details(int id)
        {
            var manager = new Manager();
            var response = manager.ViewSingleMovie(id);

            if (response.Success)
            {
                return View(response.Data);
            }
            else
                return View("Error");
        }

        public ActionResult Create()
        {
            return View();
        }

        // POST: MovieManager/Create
        [HttpPost]
        public ActionResult Create(Movie newMovie)
        {

            if (ModelState.IsValid)
            {

                Manager manager = new Manager();
                Response<Movie> response = manager.MovieAdd(newMovie);

                if (response.Success)
                {
                    return RedirectToAction("Index");
                }
                return View("Error");
            }

            return View(newMovie);

        }

        
        // GET: MovieManager/Delete
        [HttpGet]
        public ActionResult Delete(int id)
        {
            var manager = new Manager();
            var response = manager.ViewSingleMovie(id);

            if (response.Success)
            {
                var movieToDelete = response.Data;
                return View("Delete", movieToDelete);
            }
            else
            {
                return View("Error");
            }
        }

        // POST: MovieManager/Delete
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            
            Manager manager = new Manager();
            Response<Movie> response = manager.MovieDelete(id);

            if (response.Success)
            {
                return RedirectToAction("Index");
            }

            return View("Error");
        }

        [HttpGet]
        public ActionResult ViewAll(string searchString)
        {
            var manager = new Manager();
            Response<List<Movie>> response = manager.GetAllMovies(searchString);
            List<Movie> movieList = response.Data;

            if (movieList == null)
            {
                return View("Error");
            }

            return View(movieList);
        }

        [HttpPost]
        public ActionResult AddActor(string FirstName, string LastName, int movieID)
        {
            Actor newActor = new Actor();
            newActor.ActorFirstName = FirstName;
            newActor.ActorLastName = LastName;

            var manager = new Manager();
            var response = manager.AddActorToMovie(newActor, movieID);

            if (response.Success)
                return RedirectToAction("Details", new { id = movieID });
            else
                return View("Error");
        }
        
    }
}

DVD/DVDLibrary/Views/MovieManager/Create.cshtml
@model DVDLibrary.Models.Movie
@{
    ViewBag.Title = "Add a New DVD To Collection";
}

<h2>Add To Library</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Movie Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Title,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Year Released", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.ReleaseDate, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Director", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Director, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Director, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("MPAA Rating", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.MPAARating, new SelectList(new[] { "Unrated", "G", "PG", "PG-13", "R" }), "Select rating", new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.MPAARating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Studio", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Studio,  new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.Studio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("User Rating", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.UserRating, new SelectList(new[] { 0, 1, 2, 3, 4, 5 }), "Select number of stars", new {@class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserRating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("User Notes", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.UserNotes, new { @class = "form-control" } )
                @Html.ValidationMessageFor(model => model.UserNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@Html.ActionLink("Back To List", "ViewAll", "MovieManager")

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

DVD/DVDLibrary/Views/MovieManager/Delete.cshtml
@model DVDLibrary.Models.Movie
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this DVD from the collection?</h3>
<div>
    <h4>Movie</h4>
    
    <table class="table">
        <tr>
            <th>
                Title
            </th>
            <th>
                Release Date
            </th>
            <th>
                Director
            </th>
            <th>
                MPAA Rating
            </th>
            <th></th>
        </tr>
            <tr>
                <td>
                    @Html.DisplayFor(item => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(item => item.ReleaseDate)
                </td>
                <td>
                    @Html.DisplayFor(item => item.Director)
                </td>
                <td>
                    @Html.DisplayFor(item => item.MPAARating)
                </td>
               
            </tr>
    </table>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "ViewAll", "MovieManager")
            </div>
        }
</div>

DVD/DVDLibrary/Views/MovieManager/Details.cshtml
@model DVDLibrary.Models.Movie

@{
    ViewBag.Title = "Movie Details";
}


<h2>Movie Details</h2>

<table>
    <tr>
        <td><strong>Movie Title</strong></td>
        <td>@Html.DisplayFor(x => x.Title)</td>
    </tr>
    <tr>
        <td><strong>Year Released</strong></td>
        <td>@Html.DisplayFor(x => x.ReleaseDate)</td>
    </tr>
    <tr>
        <td><strong>Director</strong></td>
        <td>@Html.DisplayFor(x => x.Director)</td>
    </tr>
    <tr>
        <td><strong>MPAA Rating</strong></td>
        <td>@Html.DisplayFor(x => x.MPAARating)</td>
    </tr>
    <tr>
        <td><strong>Studio</strong></td>
        <td>@Html.DisplayFor(x => x.Studio)</td>
    </tr>
    <tr>
        <td><strong>User Rating</strong></td>
        <td>@Html.DisplayFor(x => x.UserRating) Stars</td>
    </tr>
    <tr>
        <td><strong>User Notes</strong></td>
        <td>@Html.DisplayFor(x => x.UserNotes)</td>
    </tr>
</table>
<br />
<div id="actorsGoHere">
    @if (Model.ActorsInMovie.Count != 0)
    {
        <table>
            <tr>
                <td colspan="2"><strong>Starring:</strong></td>
            </tr>
        @foreach (var a in Model.ActorsInMovie)

        {
            <tr>
                <td>@a.ActorFirstName</td>
                <td>@a.ActorLastName</td>
            </tr>
        }
        </table>
    }
    @*@using (Ajax.BeginForm("PolicyList", new AjaxOptions { UpdateTargetId = "policyList", InsertionMode = InsertionMode.Replace, HttpMethod = "GET" }))
    {
        @Html.DropDownList("category", Model.Categories, "Choose a category")
        @Html.Hidden("tableDetail", "Delete")
        <input type="submit" value="Select" />
    }*@

    <br /><h4>Add an actor to the movie</h4>
    @using (Html.BeginForm("AddActor", "MovieManager", FormMethod.Post))
    {
        <p>First name: 
        @Html.TextBox("FirstName")       
                 Last Name:
        @Html.TextBox("LastName")</p>
        @Html.HiddenFor(x => x.MovieID)
        <br />
        <input type="submit" value="Add New" />
    }
</div>

<p>
    @Html.ActionLink("Back to List", "ViewAll", "MovieManager")
</p>

DVD/DVDLibrary/Views/MovieManager/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<div class="row">
    <div class="col-sm-6 margin-top text-center col-sm-offset-3" style="margin-top: 15px;">
        <a href="@Url.Action("ViewAll", "MovieManager")" class="btn btn-primary btn-lg btn-block" style="margin-top: 20px;">
            <span class="glyphicon glyphicon-th-list" style="margin-right: 10px;">
            </span>View Library
        </a>
        <a href="@Url.Action("Create", "MovieManager")" class="btn btn-primary btn-lg btn-block" style="margin-top: 20px;">
            <span class="glyphicon glyphicon-plus" style="margin-right: 10px;">
            </span>Add to Library
        </a>
    </div>
</div>
<div class="row center-div">
    <div class="col-sm-6 text-center col-sm-offset-4">
        <div class="input-group margin-top">
            @using (Html.BeginForm("Index", "MovieManager", FormMethod.Post, new { @class = "form-group text-center" }))
            {
                <div>
                    <div class="input-group-btn" style="padding-top: 15px;">
                        <h4><label for="search" class="">Search By Title:</label></h4>
                        @using (Html.BeginForm("Index", "MovieManager", FormMethod.Get))
                        {
                            @Html.TextBox("searchString")
                            <input type="submit" value="search"> 
                        }
                    </div>
                </div>
            }
        </div>
    </div>
</div>

DVD/DVDLibrary/Views/MovieManager/SearchResult.cshtml
@model IEnumerable<DVDLibrary.Models.Movie>

@{
    ViewBag.Title = "SearchResult";
}

<h2>SearchResult</h2>

<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Release Date
        </th>
        <th>
            Director
        </th>
        <th>
            MPAA Rating
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Director)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MPAARating)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.MovieID }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.MovieID })
            </td>
        </tr>
    }

</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

DVD/DVDLibrary/Views/MovieManager/ViewAll.cshtml
@model List<DVDLibrary.Models.Movie>

@{
    ViewBag.Title = "View All Movies in Library";
}

<h2>View All Movies in Library</h2>

<p>
    @Html.ActionLink("Add New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Title
        </th>
        <th>
            Release Date
        </th>
        <th>
            Director
        </th>
        <th>
            MPAA Rating
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReleaseDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Director)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MPAARating)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.MovieID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.MovieID })
        </td>
    </tr>
}

</table>